# Generated by Django 5.1.7 on 2025-03-26 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Название запчасти.", max_length=150),
                ),
                (
                    "part_number",
                    models.CharField(
                        help_text="Артикул детали.", max_length=50, unique=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Цена запчасти.", max_digits=10
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, help_text="Количество на складе."
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Описание запчасти."),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение запчасти.",
                        null=True,
                        upload_to="auto_parts/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название категории.", max_length=100, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(help_text="Марка производителя.", max_length=100),
                ),
                (
                    "year_established",
                    models.PositiveIntegerField(
                        help_text="Год основания производителя."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата создания корзины."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Дата последнего обновления корзины."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Владелец корзины.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Количество единиц товара."
                    ),
                ),
                (
                    "auto_part",
                    models.ForeignKey(
                        help_text="Запчасть в корзине.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="reviews.autopart",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        help_text="Связанная корзина.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="reviews.cart",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="autopart",
            name="category",
            field=models.ForeignKey(
                help_text="Категория запчасти.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auto_parts",
                to="reviews.category",
            ),
        ),
        migrations.AddField(
            model_name="autopart",
            name="manufacturer",
            field=models.ForeignKey(
                help_text="Производитель запчасти.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auto_parts",
                to="reviews.manufacturer",
            ),
        ),
    ]
