# Generated by Django 5.1.7 on 2025-04-03 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="Оценка от 1 до 5.",
                    ),
                ),
                ("comment", models.TextField(blank=True, help_text="Текст отзыва.")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата создания отзыва."
                    ),
                ),
                (
                    "auto_part",
                    models.ForeignKey(
                        help_text="Запчасть, к которой относится отзыв.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="reviews.autopart",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, оставивший отзыв.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
